In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import pandas as pd
from sklearn.ensemble import IsolationForest

In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv('cleve.csv')

# Identify the outlier values based on IQR method
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
outliers = ((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)

# Remove the outlier rows from the dataset
clean_df = df[~outliers]

# Save the cleaned dataset to a new file
clean_df.to_csv('cleve_cleaned.csv', index=False)

dataset=clean_df
# Importing the dataset

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 13].values

In [4]:
#handling missing data

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')


imputer=imputer.fit(X[:,11:13])
X[:,11:13]=imputer.transform(X[:,11:13])

In [5]:
dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
2,67.0,1,4,120.0,229.0,0,2,129.0,1,2.6,2,2.0,7.0,1
3,37.0,1,3,130.0,250.0,0,0,187.0,0,3.5,3,0.0,3.0,0
4,41.0,0,2,130.0,204.0,0,2,172.0,0,1.4,1,0.0,3.0,0
5,56.0,1,2,120.0,236.0,0,0,178.0,0,0.8,1,0.0,3.0,0
6,62.0,0,4,140.0,268.0,0,2,160.0,0,3.6,3,2.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,54.0,0,3,110.0,214.0,0,0,158.0,0,1.6,2,0.0,3.0,0
297,58.0,0,4,100.0,248.0,0,2,122.0,0,1.0,2,0.0,3.0,0
299,57.0,1,4,132.0,207.0,0,0,168.0,1,0.0,1,0.0,7.0,0
301,74.0,0,2,120.0,269.0,0,2,121.0,1,0.2,1,1.0,3.0,0
302,54.0,0,3,160.0,201.0,0,0,163.0,0,0.0,1,1.0,3.0,0

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

In [9]:
# define the machine learning models to be used
svm = SVC(probability=True)
dt = DecisionTreeClassifier()
nn = MLPClassifier()
knn = KNeighborsClassifier()
nb = GaussianNB()

In [10]:
# create a list of tuples containing the name and model object for each base model
import random
import warnings
from sklearn.exceptions import ConvergenceWarning

base_models = [('svm', svm), ('dt', dt), ('nn', nn), ('knn', knn)]
from sklearn.metrics import classification_report
i=0
accuracy=0.001

while i<100:
    # ignore convergence warnings
    warnings.filterwarnings("ignore", category=ConvergenceWarning)
    random.shuffle(base_models)
    rf = RandomForestClassifier(n_estimators=100, random_state=1)

    # define the stacking classifier object
    stack = StackingClassifier(estimators=base_models, final_estimator=rf, cv=5)

    # fit the stacking classifier to the training data
    stack.fit(X_train, y_train)

    # make predictions using the stacking classifier
    y_pred = stack.predict(X_test)

    # evaluate the accuracy of the predictions
    temp = accuracy_score(y_test, y_pred)
#     print(temp)
    
    if temp>accuracy:
        accuracy=temp
        classification=classification_report(y_test, y_pred)
        
    i=i+1
print(classification)
print (accuracy)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        24
           1       0.90      0.90      0.90        20

    accuracy                           0.91        44
   macro avg       0.91      0.91      0.91        44
weighted avg       0.91      0.91      0.91        44

0.9090909090909091